from enum import StrEnum


class AnalysisFindingType(StrEnum):
    EMAIL = "email"
    FULL_NAME = "full_name"
    PHONE = "phone"
    PERSONAL_ID = "personal_id"
    PASSPORT = "passport"
    IP_ADDRESS = "ip_address"
    PASSWORD = "password"
    API_KEY = "api_key"
    TOKEN = "token"
    ACCESS_TOKEN = "access_token"
    REFRESH_TOKEN = "refresh_token"
    SESSION_ID = "session_id"
    SESSION_COOKIE = "session_cookie"
    AWS_ACCESS_KEY = "aws_access_key"
    CONNECTION_STRING = "connection_string"
    CREDIT_CARD = "credit_card"
    CVV = "cvv"
    CARD_EXPIRATION = "card_expiration"
    BANK_ACCOUNT = "bank_account"
    FINANCIAL_DATA = "financial_data"
    PRIVATE_KEY = "private_key"
    DEBUG_PAYLOAD = "debug_payload"
    PROMPT_INJECTION = "prompt_injection"
    SECRET = "secret"
    OTHER = "other"
